package cn.forever24.tutor.training;

public enum LessonAttemptStatus {
    RECEIVED,
    TRANSCRIPTION_PENDING,
    TRANSCRIPTION_RETRYABLE,
    TRANSCRIPTION_FAILED,
    ANALYSIS_PENDING,
    ANALYSIS_RETRYABLE,
    ANALYSIS_FAILED,
    ANALYZED,
    RETRY_REQUIRED,
    ACCEPTED,
    EVIDENCE_RECORDED
}
