CREATE TABLE curriculum_skill (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    skill_key VARCHAR(128) NOT NULL UNIQUE,
    name VARCHAR(160) NOT NULL,
    category VARCHAR(64) NOT NULL,
    cefr_min VARCHAR(8) NOT NULL,
    cefr_max VARCHAR(8) NOT NULL,
    importance INT NOT NULL,
    status VARCHAR(32) NOT NULL,
    created_at_utc TIMESTAMP(3) NOT NULL,
    updated_at_utc TIMESTAMP(3) NOT NULL,
    version BIGINT NOT NULL DEFAULT 0
);

CREATE TABLE curriculum_skill_edge (
    parent_skill_id BIGINT NOT NULL,
    child_skill_id BIGINT NOT NULL,
    edge_type VARCHAR(32) NOT NULL,
    PRIMARY KEY (parent_skill_id, child_skill_id, edge_type),
    FOREIGN KEY (parent_skill_id) REFERENCES curriculum_skill (id) ON DELETE CASCADE,
    FOREIGN KEY (child_skill_id) REFERENCES curriculum_skill (id) ON DELETE CASCADE
);

CREATE TABLE curriculum_skill_unit (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    skill_unit_key VARCHAR(160) NOT NULL UNIQUE,
    communication_goal VARCHAR(500) NOT NULL,
    review_template_json VARCHAR(4000) NOT NULL,
    semantic_version VARCHAR(32) NOT NULL,
    status VARCHAR(32) NOT NULL,
    created_at_utc TIMESTAMP(3) NOT NULL,
    updated_at_utc TIMESTAMP(3) NOT NULL,
    version BIGINT NOT NULL DEFAULT 0
);

CREATE TABLE curriculum_skill_unit_variant (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    variant_key VARCHAR(192) NOT NULL UNIQUE,
    skill_unit_id BIGINT NOT NULL,
    cefr_level VARCHAR(8) NOT NULL,
    communication_complexity INT NOT NULL,
    estimated_min_minutes INT NOT NULL,
    estimated_max_minutes INT NOT NULL,
    training_types_json VARCHAR(4000) NOT NULL,
    scaffolding_levels_json VARCHAR(4000) NOT NULL,
    common_error_tags_json VARCHAR(4000) NOT NULL,
    completion_policy_json VARCHAR(4000) NOT NULL,
    retry_policy_json VARCHAR(4000) NOT NULL,
    mastery_policy_json VARCHAR(4000) NOT NULL,
    status VARCHAR(32) NOT NULL,
    version BIGINT NOT NULL DEFAULT 0,
    FOREIGN KEY (skill_unit_id) REFERENCES curriculum_skill_unit (id) ON DELETE CASCADE
);

CREATE TABLE curriculum_variant_target_skill (
    variant_id BIGINT NOT NULL,
    skill_id BIGINT NOT NULL,
    role VARCHAR(32) NOT NULL,
    PRIMARY KEY (variant_id, skill_id, role),
    FOREIGN KEY (variant_id) REFERENCES curriculum_skill_unit_variant (id) ON DELETE CASCADE,
    FOREIGN KEY (skill_id) REFERENCES curriculum_skill (id)
);

CREATE TABLE curriculum_variant_prerequisite (
    variant_id BIGINT NOT NULL,
    skill_id BIGINT NOT NULL,
    minimum_mastery DECIMAL(6,5) NOT NULL,
    minimum_confidence DECIMAL(6,5) NOT NULL,
    PRIMARY KEY (variant_id, skill_id),
    FOREIGN KEY (variant_id) REFERENCES curriculum_skill_unit_variant (id) ON DELETE CASCADE,
    FOREIGN KEY (skill_id) REFERENCES curriculum_skill (id)
);

CREATE TABLE curriculum_evidence_criterion (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    criterion_key VARCHAR(128) NOT NULL,
    variant_id BIGINT NOT NULL,
    description VARCHAR(500) NOT NULL,
    weight DECIMAL(6,5) NOT NULL,
    required BOOLEAN NOT NULL,
    sequence_no INT NOT NULL,
    UNIQUE (variant_id, criterion_key),
    FOREIGN KEY (variant_id) REFERENCES curriculum_skill_unit_variant (id) ON DELETE CASCADE
);
