CREATE TABLE app_user (
    id BIGINT PRIMARY KEY,
    user_key VARCHAR(64) NOT NULL UNIQUE,
    status VARCHAR(32) NOT NULL
);

CREATE TABLE learning_plan (
    id BIGINT PRIMARY KEY,
    user_id BIGINT NOT NULL,
    plan_key VARCHAR(64) NOT NULL UNIQUE
);

CREATE TABLE learning_resource (
    id BIGINT PRIMARY KEY,
    resource_key VARCHAR(160) NOT NULL UNIQUE
);

CREATE TABLE learning_resource_version (
    id BIGINT PRIMARY KEY,
    resource_id BIGINT NOT NULL,
    semantic_version VARCHAR(32) NOT NULL
);

CREATE TABLE curriculum_skill_unit_variant (
    id BIGINT PRIMARY KEY,
    variant_key VARCHAR(192) NOT NULL
);

CREATE TABLE episode_mapping (
    id BIGINT PRIMARY KEY,
    mapping_key VARCHAR(180) NOT NULL
);

CREATE TABLE learning_task (
    id BIGINT PRIMARY KEY,
    plan_id BIGINT NOT NULL,
    task_key VARCHAR(64) NOT NULL,
    resource_version_id BIGINT,
    skill_unit_variant_id BIGINT,
    episode_mapping_id BIGINT
);

CREATE TABLE training_session (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_key VARCHAR(64) NOT NULL UNIQUE,
    user_id BIGINT NOT NULL,
    plan_id BIGINT,
    learning_task_id BIGINT,
    resource_version_id BIGINT,
    skill_unit_variant_id BIGINT,
    episode_mapping_id BIGINT,
    prescription_version BIGINT,
    idempotency_key VARCHAR(128) NOT NULL,
    start_request_hash VARCHAR(64),
    type VARCHAR(32) NOT NULL,
    mode VARCHAR(32) NOT NULL,
    status VARCHAR(32) NOT NULL,
    current_task_key VARCHAR(64) NOT NULL,
    current_step VARCHAR(48),
    step_state_json JSON,
    started_at_utc TIMESTAMP(3) NOT NULL,
    paused_at_utc TIMESTAMP(3),
    completed_at_utc TIMESTAMP(3),
    effective_seconds INT NOT NULL,
    summary_json JSON,
    created_at_utc TIMESTAMP(3) NOT NULL,
    updated_at_utc TIMESTAMP(3) NOT NULL,
    version BIGINT NOT NULL,
    UNIQUE (user_id, idempotency_key)
);

INSERT INTO app_user (id, user_key, status) VALUES
    (1, 'usr-1', 'ACTIVE'),
    (2, 'usr-2', 'ACTIVE');
INSERT INTO learning_plan (id, user_id, plan_key) VALUES (10, 1, 'prx-1');
INSERT INTO learning_resource (id, resource_key) VALUES (20, 'resource-1');
INSERT INTO learning_resource_version (id, resource_id, semantic_version) VALUES (21, 20, '1.0.0');
INSERT INTO curriculum_skill_unit_variant (id, variant_key) VALUES (30, 'skill.a2');
INSERT INTO episode_mapping (id, mapping_key) VALUES (40, 'mapping-1');
INSERT INTO learning_task
    (id, plan_id, task_key, resource_version_id, skill_unit_variant_id, episode_mapping_id)
VALUES (50, 10, 'blk-1', 21, 30, 40);
