package cn.forever24.tutor.entitlement;

public enum AccessDecisionReason {
    ALLOWED_PUBLIC,
    ALLOWED_ADMIN_GRANTED,
    ALLOWED_ADMIN_ONLY,
    RESOURCE_NOT_PUBLISHED,
    RESOURCE_DISABLED,
    COLLECTION_DISABLED,
    ACCESS_SCOPE_DISABLED,
    ADMIN_ONLY,
    ENTITLEMENT_REQUIRED,
    ENTITLEMENT_REVOKED,
    ENTITLEMENT_EXPIRED,
    ENTITLEMENT_OWNERSHIP_MISMATCH
}
